name: hiblob_example
description: Interactive studio for the local hiblob Dart and Flutter SDK.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  hiblob:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
